#spring.application.name=demo
server:
  port: 8080

spring:
  datasource:
#    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
#    username: ${MYSQLUSER}
#    password: ${MYSQLPASSWORD}
    url: jdbc:mysql://mysql.railway.internal:3306/railway
    username: root
    password: PsfeCxEshnWPZLEPYeoEvhpEiNcHEafJ
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity
